FROM mysql:latest


ENV MYSQL_ROOT_PASSWORD=password


ENV MYSQL_DATABASE=mydatabase
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=password


# Expose the MySQL port
EXPOSE 3307


# Start MySQL service automatically when the container starts
CMD ["mysqld"]
